name: app_raptor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0 <3.6.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/perfil.png
    - assets/tenis/jordan4.png
    - assets/tenis/adi2000.png
    - assets/tenis/mizuno.png
    - assets/tenis/vansKnow.png
    - assets/tenis/pumaSuedeXL.png
    - assets/tenis/puma180.png
    - assets/tenis/airforce1.webp
    - assets/tenis/badbunny.webp
    - assets/tenis/hocksbold.jpg